package.json, packages/ckeditor5-package-generator/lib/index.js, packages/ckeditor5-package-generator/lib/templates/.gitignore
Fix (generator): Create `.gitignore` file manually when bootstrapping a new package. Closes #50.
Internal: Due to different results when publishing packages using npm, use the latest version to publish all files.
=> Create .gitignore file manually when bootstrapping a new package

packages/ckeditor5-package-generator/lib/index.js, packages/ckeditor5-package-generator/lib/utils/validate-package-name.js, packages/ckeditor5-package-generator/tests/utils/validate-package-name.js
Other (generator): Improved an error when no package name was specified during the command execution. Closes #72.
=> Changed handling of empty package name

.travis.yml, README.md, package.json, packages/ckeditor5-package-tools/lib/utils/get-karma-config.js, packages/ckeditor5-package-tools/tests/utils/get-karma-config.js, packages/ckeditor5-package-tools/tests/utils/get-webpack-config-server.js
Internal: Added integration with `Coveralls.io` service. Closes #81.
---
I've added a few tests, because on CI the coverage was below 100%.
=> Integration with `Coveralls.io` service

packages/ckeditor5-package-generator/lib/templates/package.json
Other (generator): Upgraded the `http-server` package to the latest version to fix a problem with starting the HTTP server for DLL files. Closes #87.
=> Fixed `dll:serve` script in the generated package.

packages/ckeditor5-package-generator/package.json
Fix (generator): Added the missing `webpack` dependency to the `package.json` file. It fixes the _Cannot find module 'webpack'_ error. The `@ckeditor/ckeditor5-dev-utils` dependency defines peer dependencies, which must be installed manually in the generator package. Closes #89.
=> Added webpack to dependencies.

.eslintrc.js, package.json
Internal: Allowed the "license-header" ESLint rule. See ckeditor/ckeditor5#11468.
=> Allowed the "license-header" ESLint rule

package.json, packages/ckeditor5-package-generator/package.json, packages/ckeditor5-package-tools/lib/tasks/translations-download.js, packages/ckeditor5-package-tools/lib/tasks/translations-upload.js, packages/ckeditor5-package-tools/lib/utils/parse-arguments.js, packages/ckeditor5-package-tools/package.json, packages/ckeditor5-package-tools/tests/tasks/translations-download.js, packages/ckeditor5-package-tools/tests/tasks/translations-upload.js, packages/ckeditor5-package-tools/tests/utils/parse-arguments.js
Other (tools): Aligned the translations tools to the new API exported by the `@ckeditor/ckeditor5-dev-env` package. Closes #71.
MAJOR BREAKING CHANGES (tools): The `-- transifex [API end-point]` option is no longer supported. Use the following options: `--organization [organization name]` and `--project [project name]` instead.
---
* Requires: https://github.com/ckeditor/ckeditor5-dev/pull/761
=> Aligned the translations tools to the new API

package.json, packages/ckeditor5-package-generator/package.json, packages/ckeditor5-package-tools/package.json
Other: Packages generated by the tool use PostCSS@8 now. See ckeditor/ckeditor5#11460.
---
=> Upgraded the `postcss` version to 8

packages/ckeditor5-package-generator/lib/templates/src/myplugin.js
Fix (generator): Removed the `isToggleable` property from the plugin template. Closes #97.
---
I checked tests (they pass) but I didn't generate a package with this change to ensure that it's working as expected.
=> Removed isToggleable property from the template

packages/ckeditor5-package-generator/lib/templates/package.json, packages/ckeditor5-package-generator/lib/utils/get-dependencies-versions.js, packages/ckeditor5-package-generator/tests/utils/get-dependencies-versions.js
Fix (generator): When creating a new package, a version of the `@ckeditor/ckeditor5-inspector` package should be taken from the npm registry. Closes #96.
---
=> Get the latest inspector version from npm

packages/ckeditor5-package-tools/lib/tasks/translations-collect.js, packages/ckeditor5-package-tools/tests/tasks/translations-collect.js, scripts/ci/travis-check.js
Feature: Added support for collecting translation entries from TypeScript files. Closes #106.
---
=> Added support for collecting translation entries from TypeScript files

README.md, packages/ckeditor5-package-generator/README.md, packages/ckeditor5-package-generator/bin/index.js, packages/ckeditor5-package-generator/lib/index.js, packages/ckeditor5-package-generator/lib/utils/choose-package-manager.js, packages/ckeditor5-package-generator/lib/utils/install-dependencies.js, packages/ckeditor5-package-generator/lib/utils/is-yarn-installed.js, packages/ckeditor5-package-generator/tests/index.js, packages/ckeditor5-package-generator/tests/utils/choose-package-manager.js, packages/ckeditor5-package-generator/tests/utils/install-dependencies.js, packages/ckeditor5-package-generator/tests/utils/is-yarn-installed.js, scripts/ci/travis-check.js
Other (generator): Added `--use-yarn` flag to package generator to use yarn for installing dependencies in a newly created package. If npm and yarn are installed and no flags are set, user is prompted for a choice. Closes #120
=> Added --use-yarn flag to package generator and set it to true by default when yarn is installed

packages/ckeditor5-package-tools/lib/tasks/translations-download.js, packages/ckeditor5-package-tools/lib/tasks/translations-upload.js, packages/ckeditor5-package-tools/lib/utils/get-webpack-config-dll.js, packages/ckeditor5-package-tools/tests/tasks/translations-download.js, packages/ckeditor5-package-tools/tests/tasks/translations-upload.js, packages/ckeditor5-package-tools/tests/utils/get-webpack-config-dll.js
Fix (tools): Added support for package names without organization prefix. Closes #139.
---
=> Package tools will now support package names without organization prefix

packages/ckeditor5-package-generator/lib/utils/get-package-name-formats.js, packages/ckeditor5-package-tools/lib/utils/get-karma-config.js, packages/ckeditor5-package-tools/lib/utils/get-webpack-config-dll.js, packages/ckeditor5-package-tools/lib/utils/get-webpack-config-server.js, packages/ckeditor5-package-tools/lib/utils/webpack-utils.js, packages/ckeditor5-package-tools/package.json, packages/ckeditor5-package-tools/tests/utils/get-karma-config.js, packages/ckeditor5-package-tools/tests/utils/get-webpack-config-dll.js, packages/ckeditor5-package-tools/tests/utils/get-webpack-config-server.js, packages/ckeditor5-package-tools/tests/utils/webpack-utils.js, scripts/ci/travis-check.js
Fix (tools): Added the missing `ts-loader`. Webpack missed it when creating a new package using `npm` as the package manager. Closes #143.
---
=> Added missing ts-loader

packages/ckeditor5-package-tools/package.json
Other (tools): Update `terser-webpack-plugin` to enable optional chaining syntax. Closes #136.
---
=> Update `terser-webpack-plugin` to enable optional chaining syntax.

packages/ckeditor5-package-generator/lib/templates/ts/sample/index.html, packages/ckeditor5-package-generator/lib/templates/ts/src/_PLACEHOLDER_.ts.txt, packages/ckeditor5-package-generator/lib/templates/ts/src/augmentation.ts.txt, packages/ckeditor5-package-generator/lib/templates/ts/src/index.ts.txt, packages/ckeditor5-package-generator/lib/templates/ts/tsconfig.json.txt, scripts/ci/travis-check.js
Feature: Add `augmentation.ts` to the TypeScript package generator. Closes ckeditor/ckeditor5-package-generator#144.
---
=> Add `augmentation.ts` to the TypeScript package generator.

packages/ckeditor5-package-generator/lib/utils/choose-programming-language.js, packages/ckeditor5-package-generator/tests/utils/choose-programming-language.js
Other (generator): Removed the "experimental" label from TS and made it the default choice. Related #111.
=> Removed the experimental label from TS

packages/ckeditor5-package-generator/bin/index.js
Feature (generator): The tool will now display its version when used with `-V`/`--version` option. The version will also be displayed on the `-h`/`--help` message. Closes #150.
---
=> Added option to check version of the generator

packages/ckeditor5-package-generator/lib/utils/get-package-version.js, packages/ckeditor5-package-generator/tests/utils/get-package-version.js
Other (generator): When generating a new package, the generator uses the latest stable CKEditor 5 release. Closes #155.
---
=> Use the `@latest` release when looking for CKEditor 5 version

packages/ckeditor5-package-generator/lib/utils/install-dependencies.js, packages/ckeditor5-package-generator/tests/utils/install-dependencies.js
Fix (generator): Removed the current working directory from a package manager command when installing dependencies. A new process is already spawned in the directory. Hence, there is no need to duplicate the path. Thanks to that, a space in the path will not crash the generator while installing dependencies. Closes #156.
---
=> Space in a path does not crash the generator

.circleci/config.yml, scripts/ci/verify-build.js
Internal: Fixed script that creates test build on CI where the path to `ckeditor5-package-generator` is different than locally.
Internal: Fixed incorrect launching of the dev server on CI.
Internal: Changed sending the coverage status to be the last step on CI.
---
=> Fixed path to `ckeditor5-package-generator` that is different on CI than locally

package.json, packages/ckeditor5-package-generator/lib/templates/js/package.json, packages/ckeditor5-package-generator/lib/templates/ts/package.json, packages/ckeditor5-package-generator/package.json
Other: Updated the required version of Node.js to 18. See ckeditor/ckeditor5#14924.
MAJOR BREAKING CHANGE: Upgraded the minimal versions of Node.js to `18.0.0` due to the end of LTS.
=> Node version bump

package-lock.json, packages/ckeditor5-package-generator/lib/utils/copy-files.js, packages/ckeditor5-package-generator/package.json, packages/ckeditor5-package-tools/package.json
Other: Updated `webpack-dev-server`, `stylelint` and `lodash` to fix vulnerability alert. See cksource/ckeditor5-internal#3715.
---
=> Updated `webpack-dev-server`, `stylelint` and `lodash` to fix vulnerability alert.

README.md, package-lock.json, scripts/ci/is-project-ready-to-release.js, scripts/release/publishpackages.js, scripts/release/utils/parsearguments.js
Internal: Support for releasing the repository for prereleases.
---
Part of https://github.com/cksource/ckeditor5-internal/issues/3710.
=> Support for prereleases released via CI.

packages/ckeditor5-package-generator/lib/templates/ts-legacy/package.json, packages/ckeditor5-package-generator/lib/templates/ts/package.json, scripts/ci/utils/expectedFiles.js, scripts/ci/verify-build.js
Fix (generator): Change the path to the types in the `package.json`  in `ts` templates. See https://github.com/ckeditor/ckeditor5/issues/16684.
---
=> Change the path to the types in the `package.json` in `ts` templates.

packages/ckeditor5-package-generator/lib/templates/js-legacy/package.json, packages/ckeditor5-package-generator/lib/templates/js/package.json, packages/ckeditor5-package-generator/lib/templates/ts-legacy/package.json, packages/ckeditor5-package-generator/lib/templates/ts/package.json
Fix (generator): Update the `exports` field in `package.json` templates to fix issues with loading CSS and translations in older bundlers. See https://github.com/ckeditor/ckeditor5/issues/16638.
---
=> Update the `exports` field in `package.json` templates to fix issues with loading CSS and translations in older bundlers.

packages/ckeditor5-package-generator/lib/templates/js-legacy/README.md, packages/ckeditor5-package-generator/lib/templates/js/README.md, packages/ckeditor5-package-generator/lib/templates/ts-legacy/README.md, packages/ckeditor5-package-generator/lib/templates/ts/README.md
Fix (generator): Each package template should have own `README.md` based on what commands can be execute in it. Closes https://github.com/ckeditor/ckeditor5-package-generator/issues/174.
---
=> Each package template should have own `README.md` based on what commands can be execute in it.

packages/ckeditor5-package-generator/lib/utils/get-dependencies-versions.js, packages/ckeditor5-package-generator/tests/utils/get-dependencies-versions.js
Other (generator): Lock to the last compatible version of the `@ckeditor/ckeditor5-dev-build-tools` package due to the upcoming release of breaking changes in the `@ckeditor/ckeditor5-dev-*` packages. Closes #191.
---
=> Lock to the last compatible version of the `@ckeditor/ckeditor5-dev-build-tools` package

packages/ckeditor5-package-generator/lib/templates/common/ckeditor5-metadata.json, packages/ckeditor5-package-generator/lib/templates/js-legacy/sample/ckeditor.js.txt, packages/ckeditor5-package-generator/lib/templates/js-legacy/sample/dll.html.txt, packages/ckeditor5-package-generator/lib/templates/js-legacy/src/_PLACEHOLDER_.js.txt, packages/ckeditor5-package-generator/lib/templates/js-legacy/tests/_PLACEHOLDER_.js.txt, packages/ckeditor5-package-generator/lib/templates/js/sample/ckeditor.js.txt, packages/ckeditor5-package-generator/lib/templates/js/src/_PLACEHOLDER_.js.txt, packages/ckeditor5-package-generator/lib/templates/js/tests/_PLACEHOLDER_.js.txt, packages/ckeditor5-package-generator/lib/templates/ts-legacy/sample/ckeditor.ts.txt, packages/ckeditor5-package-generator/lib/templates/ts-legacy/sample/dll.html.txt, packages/ckeditor5-package-generator/lib/templates/ts-legacy/src/_PLACEHOLDER_.ts.txt, packages/ckeditor5-package-generator/lib/templates/ts-legacy/tests/_PLACEHOLDER_.ts.txt, packages/ckeditor5-package-generator/lib/templates/ts/sample/ckeditor.ts.txt, packages/ckeditor5-package-generator/lib/templates/ts/sample/dll.html.txt, packages/ckeditor5-package-generator/lib/templates/ts/src/_PLACEHOLDER_.ts.txt, packages/ckeditor5-package-generator/lib/templates/ts/tests/_PLACEHOLDER_.ts.txt
Other (generator): Aligned the UI component name from the generated package to naming convention in CKEditor 5. Closes #209.
---
=> Aligned the UI component name to naming convention in CKEditor 5

packages/ckeditor5-package-generator/lib/index.js, packages/ckeditor5-package-generator/lib/utils/set-global-name.js, packages/ckeditor5-package-generator/tests/index.js, packages/ckeditor5-package-generator/tests/utils/set-global-name.js
Other (generator): The package generator prompt displays the suggested name for the UMD build. The name is created from the plugin name and prefixed with the `CK`. Closes #207.
---
Package generator suggests now the global name for the UMD build. Assuming that the name of the package being created is `@test-scope/ckeditor5-custom-plugin`, the package generator suggests `CKCustomPlugin` as the default UMD name:
```
? Enter the global name for UMD build: (CKCustomPlugin)
```
=> Display suggested global name for UMD build from the plugin name

package.json
Internal: Restored the missing `--quiet` parameter for a pre-commit hook
Part of https://github.com/cksource/ckeditor5-internal/issues/4027.
=> Restored the missing `--quiet` parameter for a pre-commit hook

packages/ckeditor5-package-generator/lib/templates/js-legacy/package.json, packages/ckeditor5-package-generator/lib/templates/js/package.json, packages/ckeditor5-package-generator/lib/templates/ts-legacy/package.json, packages/ckeditor5-package-generator/lib/templates/ts/package.json
Other (generator): The Stylelint version in the generated packages has been bumped to v16.x.
---
=> Bump Stylelint to v16.x

.circleci/config.yml, packages/ckeditor5-package-generator/bin/index.js, packages/ckeditor5-package-generator/lib/utils/copy-files.js, packages/ckeditor5-package-generator/lib/utils/create-directory.js, packages/ckeditor5-package-generator/lib/utils/get-dependencies-versions.js, packages/ckeditor5-package-generator/lib/utils/initialize-git-repository.js, packages/ckeditor5-package-generator/tests/utils/copy-files.js, packages/ckeditor5-package-generator/tests/utils/create-directory.js, packages/ckeditor5-package-generator/tests/utils/get-dependencies-versions.js, packages/ckeditor5-package-generator/tests/utils/initialize-git-repository.js, packages/ckeditor5-package-tools/lib/tasks/synchronize-translations.js, packages/ckeditor5-package-tools/lib/utils/get-path.js, packages/ckeditor5-package-tools/lib/utils/get-webpack-config-dll.js, packages/ckeditor5-package-tools/lib/utils/get-webpack-config-server.js, packages/ckeditor5-package-tools/lib/utils/update-entry-point.js, packages/ckeditor5-package-tools/lib/utils/webpack-utils.js, packages/ckeditor5-package-tools/package.json, packages/ckeditor5-package-tools/tests/tasks/synchronize-translations.js, packages/ckeditor5-package-tools/tests/utils/get-webpack-config-dll.js, packages/ckeditor5-package-tools/tests/utils/get-webpack-config-server.js, packages/ckeditor5-package-tools/tests/utils/update-entry-point.js, packages/ckeditor5-package-tools/tests/utils/webpack-utils.js, pnpm-lock.yaml, scripts/ci/verify-build.js, scripts/postinstall.js, scripts/release/utils/constants.js
Replaced `path` package with `upath` to ensure that all paths are normalized.
---
* Closes #254
---
*Optional: Notes on decisions, edge cases, or anything helpful for reviewers.*
=> Replaced `path` package with `upath` to ensure that all paths are normalized
