README.md, packages/ckeditor5-package-generator/lib/index.js, packages/ckeditor5-package-generator/lib/templates/ckeditor5-metadata.json
Other: Added ckeditor5-metadata.json file in template files. Closes #46.
=> Added ckeditor5-metadata.json file in template files

packages/ckeditor5-package-generator/lib/templates/package.json, packages/ckeditor5-package-generator/lib/templates/sample/ckeditor.js
Other: Enabled inspector in the manual test sample. Closes #58.
=> Enabled inspector in the manual test sample.

packages/ckeditor5-package-generator/lib/index.js, packages/ckeditor5-package-generator/lib/templates/.eslintrc.js, packages/ckeditor5-package-generator/lib/templates/package.json
Other: Enabled verifying a commit using husky in a newly created package. Closes #59.
=> Enabled verifying a commit using husky in a newly created package

scripts/ci/travis-check.js
Internal: Unified process termination on different operating systems. Closes #79.
---
=> Unified process termination on different operating systems

packages/ckeditor5-package-generator/README.md
Other (generator): Added mandatory requirement for minimum `Node.js` version and optional requirement for globally installed `yarn`. Closes #82.
=> Listed the requirements.

packages/ckeditor5-package-generator/lib/templates/js/package.json, packages/ckeditor5-package-generator/lib/templates/ts/package.json, scripts/ci/travis-check.js
Internal: Added check for the "publish" process on CI. Closes #118.
---
=> Added check for the "publish" process on CI.

packages/ckeditor5-package-generator/lib/utils/choose-programming-language.js, packages/ckeditor5-package-generator/tests/utils/choose-programming-language.js
Internal: Added label "experimental" to TypeScript in package generator CLI. Closes #123.
=> Feat (package-generator): Add label experimental to typescript in package generator cli

.husky/pre-commit, package.json, packages/ckeditor5-package-generator/lib/templates/ts/package.json, scripts/postinstall.js
Internal: Upgraded husky to v8.
=> Upgraded husky to v8

.travis.yml, package.json
Internal: Use `ckeditor5-dev-ci-notify-travis-status` script from new package `ckeditor5-dev-ci`.
---
=> Use `ckeditor5-dev-ci-notify-travis-status` script from new package `ckeditor5-dev-ci`

.travis.yml, packages/ckeditor5-package-tools/lib/utils/get-karma-config.js, packages/ckeditor5-package-tools/tests/utils/get-karma-config.js
Internal: Added the `--openssl-legacy-provider` modifier to Node options on CI.
=> Fix "error:0308010C:digital envelope routines::unsupported"

package.json
Internal: Bumped dependencies.
---
=> Bumped deps.

package-lock.json
Other: Fixed dependabot alerts & changed to `yarn.lock` instead of `package-json.lock`. See cksource/ckeditor5-internal#3715.
---
=> Fixed dependabot alerts & changed to `yarn.lock` instead of `package-json.lock`.

CHANGELOG.md
Internal: Changelog for v2.1.0.
---
=> Changelog for v2.1.0

CHANGELOG.md
Internal: Changelog for v3.0.0-alpha.0.
---
=> Changelog for v3.0.0-alpha.0

package.json, packages/ckeditor5-package-tools/package.json, yarn.lock
Internal: Updated dependency versions to remove warnings.
---
=> Updated dependency versions to remove warnings.

.circleci/config.yml, CHANGELOG.md, scripts/release/utils/parsearguments.js
Internal: Changelog for v2.1.1.
---
=> Changelog for v2.1.1

CHANGELOG.md
Internal: Copied changelog entries for `v2.1.1`.
---
=> Changelog entries for v2.1.1 (to master)

CHANGELOG.md
Internal: Changelog for v3.0.0.
---
=> Changelog for v3.0.0

scripts/release/publishpackages.js
Internal: Removed non-existing release task.
---
=> Removed non-existing release task

packages/ckeditor5-package-generator/lib/templates/js-legacy/sample/ckeditor.js.txt, packages/ckeditor5-package-generator/lib/templates/js-legacy/sample/dll.html.txt, packages/ckeditor5-package-generator/lib/templates/js-legacy/tests/_PLACEHOLDER_.js.txt, packages/ckeditor5-package-generator/lib/templates/js/sample/ckeditor.js.txt, packages/ckeditor5-package-generator/lib/templates/js/tests/_PLACEHOLDER_.js.txt, packages/ckeditor5-package-generator/lib/templates/ts-legacy/sample/ckeditor.ts.txt, packages/ckeditor5-package-generator/lib/templates/ts-legacy/sample/dll.html.txt, packages/ckeditor5-package-generator/lib/templates/ts-legacy/tests/_PLACEHOLDER_.ts.txt, packages/ckeditor5-package-generator/lib/templates/ts/sample/ckeditor.ts.txt, packages/ckeditor5-package-generator/lib/templates/ts/tests/_PLACEHOLDER_.ts.txt
Other (package-generator): Added `GPL` licenseKey to the packages created by the generator. Closes #201.
---
=> Addded `GPL` licenseKey to the packages created by the generator.

scripts/ci/is-project-ready-to-release.js
Internal: Improved the detection to release script by passing a valid package name. Closes #203.
---
=> Improved the detection to release script by passing a valid package name

yarn.lock
Internal: Fresh `yarn.lock`.
---
=> Fresh `yarn.lock`

CHANGELOG.md
Internal: Changelog for v3.0.1.
---
=> Changelog for v3.0.1

yarn.lock
Internal: Update dependencies.
=> Internal: Update dependencies.

package.json, scripts/ci/verify-build.js, yarn.lock
Internal: Update dependencies.
Internal: Remove `strip-ansi` dependency and use Node native API instead.
=> Other: Update dependencies.

CHANGELOG.md
Internal: Changelog for v4.0.0.
---
=> Changelog for v4.0.0

packages/ckeditor5-package-tools/lib/utils/get-webpack-config-dll.js, packages/ckeditor5-package-tools/lib/utils/get-webpack-config-server.js, packages/ckeditor5-package-tools/lib/utils/webpack-utils.js, packages/ckeditor5-package-tools/tests/utils/get-webpack-config-dll.js, packages/ckeditor5-package-tools/tests/utils/get-webpack-config-server.js, packages/ckeditor5-package-tools/tests/utils/webpack-utils.js
Other (package-tools): Add support for importing raw file content by appending `?raw` query parameter to import path. Closes #235.
---
=> Support for importing raw file content by appending `?raw`

CHANGELOG.md
Internal: Changelog for v4.0.1.
---
=> Changelog for v4.0.1

.changelog/20250716155339_package_generator_132_fix_use_in_monorepo.md, CHANGELOG.md
Changelog for v4.0.2.
---
* Closes #000
---
*Optional: Notes on decisions, edge cases, or anything helpful for reviewers.*
=> Changelog for v4.0.2

packages/ckeditor5-package-generator/package.json, yarn.lock
Bumped dependencies
---
* Closes #000
---
https://github.com/SBoudrias/Inquirer.js/releases/tag/inquirer%4012.0.0
=> Bumped dependencies
